### ISSUE TITLE
Comments are not in cronological order

### ISSUE THREAD

**Issue by the-maldridge** [ConstellationApps/TicketBox#16]
When a new comment is added it shows up at the bottom but on page refresh the comments are in reverse cronological order.  This is a blocker for #15

**Comment by tdorianh** [comment]
I am unable to duplicate this issue. I created a new ticket and added replies; replies posted chronologically and loaded chronologically upon refresh. 

I added 8 replies with the following bodies in this order:
1
2
3
abc
def
ghi
1
6

Upon refreshing they were still listed exactly in the order I created them.

**Comment by dinoocch** [comment]
https://github.com/ConstellationApps/TicketBox/blob/master/constellation_ticketbox/models.py#L7

Add something like:
```
class Meta:
    ordering = ['timestamp']
```
That should help probably

**Comment by tdorianh** [comment]
Resolved in 6d01e22
