### ISSUE TITLE
Multiple inboxes

### ISSUE THREAD

**Issue by the-maldridge** [ConstellationApps/TicketBox#2]
It should be possible to create multiple inboxes with distinct names and groups which process the submitted cards.  This can be thought of as multiple ticket queues wherein each queue may have multiple groups that are permitted to respond.  It should also be possible to specify what groups a box is visible to for tickets to be submitted.

Like tickets, boxes can never be deleted, only archived.

**Comment by tdorianh** [comment]
Resolved in 679f370, 935d76c, 1c8ebd8
