### ISSUE TITLE
Anonymous checkbox on new ticket is not material

### ISSUE THREAD

**Issue by m-wynn** [ConstellationApps/TicketBox#21]
It should be more in line and use the mdl [checkbox](https://getmdl.io/components/index.html#toggles-section/checkbox) classes
#15

**Comment by the-maldridge** [comment]
@m-wynn I'm happy with the mdl branch, can you sign off on this?

**Comment by m-wynn** [comment]
The html that is rendered from
```html
<input type="checkbox" id={{form.anonymous.id_for_label}} class="mdl-switch__input"{{form.anonymous}}
```
is very invalid.

The end result needs to look something like
```html
<label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="{{ form.anonymous.id_for_label }}">
{{form.anonymous}}
<span class="mdl-radio__label">Anonymous</span>
</label>
```
and forms.py needs to be updated to have something like
```python
self.fields['anonymous'].widget.attrs['class'] = 'mdl-switch__input'
```
and the for-loop needs to be modified to either not set the `mdl-textfield__input` on the anonymous field, or, instead of a for-loop, use similar code to the python I just gave to set `mdl-textfield__input` on the text fields individually (instead of blindly applying to all).

**Comment by tdorianh** [comment]
The mdl branch is temporary; I forgot to remove it. (My bad.) I am going to make the proper/legitimate changes to formatting and HTML on another branch.
