### ISSUE TITLE
Ticket view should be formatted more nicely

### ISSUE THREAD

**Issue by m-wynn** [ConstellationApps/TicketBox#24]
There are a few UX paradigms you could use for this.

- [CV Welcome](https://welcome.collegiumv.org) -- The icon/card/arrow here is a good way to show progress
- Github comments -- This has a clear delimiter for meta information (status, date submitter) vs title and content vs actions.  It's not super, but the fact that these three are separate is important

#15

**Comment by tdorianh** [comment]
Resolved in 01abac5, ee12818
