### ISSUE TITLE
Close Tickets

### ISSUE THREAD

**Issue by the-maldridge** [ConstellationApps/TicketBox#4]
A user with administrative power should be able to close a ticket with a message and/or status.  Possible statuses may include "resolved", "deferred", "closed", "rejected", etc.  Perhaps statuses can be created at a later date.

The owner of a ticket should be able to close it at any time.  Closing a ticket does not delete it.  A closed ticket simply becomes archived and is still visible in an "archived tickets" view.

**Comment by tdorianh** [comment]
Resolved in b4eeac3, c0a3b88, dff63a9
