### ISSUE TITLE
Anonymous Tickets

### ISSUE THREAD

**Issue by the-maldridge** [ConstellationApps/TicketBox#7]
A ticket owner should be able to submit a ticket anonymously.  This still logs who submitted the ticket to the database and the information is still available to superusers (since they bypass all permissions), but to normal users replying to the ticket the identity of the owner should be obscured.  It should be possible to reply to an anonymous ticket.

**Comment by tdorianh** [comment]
Resolved in 136bdc4, ae19441, 4a8c57e
